# Generated by Django 3.0.1 on 2020-01-03 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pair', models.IntegerField(blank=True, db_column='id_pair', null=True)),
                ('price', models.TextField(blank=True, db_column='Price', null=True)),
                ('timestamp', models.TextField(blank=True, db_column='TimeStamp', null=True)),
                ('volume', models.TextField(blank=True, db_column='Volume', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.TextField(blank=True, db_column='Volume', null=True)),
                ('price', models.TextField(blank=True, db_column='Price', null=True)),
                ('timestamp', models.TextField(blank=True, db_column='TimeStamp', null=True)),
                ('id_pair', models.IntegerField(blank=True, db_column='id_pair', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bots',
            fields=[
                ('robot', models.AutoField(primary_key=True, serialize=False)),
                ('market_orders', models.BooleanField()),
                ('freq', models.DecimalField(decimal_places=3, max_digits=10)),
                ('max_orders', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pairs',
            fields=[
                ('id_pair', models.AutoField(primary_key=True, serialize=False)),
                ('buy_pair', models.CharField(max_length=100)),
                ('sell_pair', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('timestamp', models.TextField()),
                ('volume', models.FloatField()),
                ('price', models.FloatField()),
                ('buy', models.BooleanField(default=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tradeview.Pairs')),
            ],
        ),
        migrations.CreateModel(
            name='LocalBids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('timestamp', models.TextField()),
                ('volume', models.FloatField()),
                ('price', models.FloatField()),
                ('buy', models.BooleanField(default=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tradeview.Pairs')),
            ],
        ),
    ]
