# Generated by Django 3.0.1 on 2020-01-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='buyer',
            field=models.CharField(default='2', max_length=100),
        ),
        migrations.AddField(
            model_name='trades',
            name='seller',
            field=models.CharField(default='API', max_length=100),
        ),
    ]
