# Generated by Django 3.0.1 on 2020-01-04 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradeview', '0002_auto_20200104_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trades',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='seller',
        ),
    ]
