version: '3'

services:
  web:
    build: .
    command: bash -c "exec python data_pull.py & exec python manage.py runserver 0.0.0.0:8000"
    #"python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: crypto_exchange
    volumes:
      - .:/crypto_exchange
    ports:
      - "8000:8000"